import { Contract, constants } from "ethers";
import { JsonRpcProvider, Web3Provider } from "@ethersproject/providers";
declare type MinifiedContracts = {
    [key: string]: {
        abi?: any;
        bin?: any;
    };
};
export default class Fuse {
    provider: JsonRpcProvider;
    constants: typeof constants;
    contracts: {
        [key: string]: Contract;
    };
    compoundContracts: MinifiedContracts;
    openOracleContracts: MinifiedContracts;
    oracleContracts: MinifiedContracts;
    getEthUsdPriceBN: any;
    identifyPriceOracle: any;
    deployPool: any;
    deployPriceOracle: any;
    deployComptroller: any;
    deployAsset: any;
    deployInterestRateModel: any;
    deployCToken: any;
    deployCEther: any;
    deployCErc20: any;
    identifyInterestRateModel: any;
    getInterestRateModel: any;
    checkForCErc20PriceFeed: any;
    getPriceOracle: any;
    deployRewardsDistributor: any;
    checkCardinality: any;
    primeUniswapV3Oracle: any;
    identifyInterestRateModelName: any;
    static FUSE_POOL_DIRECTORY_CONTRACT_ADDRESS: string;
    static FUSE_SAFE_LIQUIDATOR_CONTRACT_ADDRESS: string;
    static FUSE_FEE_DISTRIBUTOR_CONTRACT_ADDRESS: string;
    static FUSE_POOL_LENS_CONTRACT_ADDRESS: string;
    static FUSE_POOL_LENS_SECONDARY_CONTRACT_ADDRESS: string;
    static COMPTROLLER_IMPLEMENTATION_CONTRACT_ADDRESS: string;
    static CERC20_DELEGATE_CONTRACT_ADDRESS: string;
    static CETHER_DELEGATE_CONTRACT_ADDRESS: string;
    static REWARDS_DISTRIBUTOR_DELEGATE_CONTRACT_ADDRESS: string;
    static MASTER_PRICE_ORACLE_IMPLEMENTATION_CONTRACT_ADDRESS: string;
    static INITIALIZABLE_CLONES_CONTRACT_ADDRESS: string;
    static OPEN_ORACLE_PRICE_DATA_CONTRACT_ADDRESS: string;
    static COINBASE_PRO_REPORTER_ADDRESS: string;
    static PUBLIC_PRICE_ORACLE_CONTRACT_ADDRESSES: {
        ChainlinkPriceOracle: string;
        ChainlinkPriceOracleV2: string;
        ChainlinkPriceOracleV3: string;
        UniswapTwapPriceOracle_Uniswap: string;
        UniswapTwapPriceOracle_SushiSwap: string;
        UniswapLpTokenPriceOracle: string;
        UniswapV3TwapPriceOracle_Uniswap_3000: string;
        UniswapV3TwapPriceOracle_Uniswap_10000: string;
        UniswapV3TwapPriceOracleV2_Uniswap_500_USDC: string;
        UniswapV3TwapPriceOracleV2_Uniswap_3000_USDC: string;
        UniswapV3TwapPriceOracleV2_Uniswap_10000_USDC: string;
        YVaultV1PriceOracle: string;
        YVaultV2PriceOracle: string;
        MasterPriceOracle: string;
        CurveLpTokenPriceOracle: string;
        CurveLiquidityGaugeV2PriceOracle: string;
        FixedEthPriceOracle: string;
        FixedEurPriceOracle: string;
        WSTEthPriceOracle: string;
        FixedTokenPriceOracle_OHM: string;
        UniswapTwapPriceOracleV2_SushiSwap_DAI: string;
        UniswapTwapPriceOracleV2_SushiSwap_CRV: string;
        UniswapTwapPriceOracleV2_SushiSwap_USDC: string;
        UniswapTwapPriceOracleV2_Uniswap_FRAX: string;
        SushiBarPriceOracle: string;
        BadgerPriceOracle: string;
        HarvestPriceOracle: string;
        StakedSdtPriceOracle: string;
        TokemakPoolTAssetPriceOracle: string;
        MStablePriceOracle: string;
    };
    static UNISWAP_TWAP_PRICE_ORACLE_ROOT_CONTRACT_ADDRESS: string;
    static UNISWAP_TWAP_PRICE_ORACLE_V2_ROOT_CONTRACT_ADDRESS: string;
    static UNISWAP_TWAP_PRICE_ORACLE_V2_FACTORY_CONTRACT_ADDRESS: string;
    static UNISWAP_V3_TWAP_PRICE_ORACLE_V2_FACTORY_CONTRACT_ADDRESS: string;
    static DAI_POT: string;
    static DAI_JUG: string;
    static UNISWAP_V2_FACTORY_ADDRESS: string;
    static UNISWAP_V2_PAIR_INIT_CODE_HASH: string;
    static SUSHISWAP_FACTORY_ADDRESS: string;
    static UNISWAP_V3_FACTORY_ADDRESS: string;
    static WETH_ADDRESS: string;
    static PRICE_ORACLE_RUNTIME_BYTECODE_HASHES: {
        ChainlinkPriceOracle: string;
        ChainlinkPriceOracleV2: string;
        ChainlinkPriceOracleV3: string;
        UniswapTwapPriceOracle_Uniswap: string;
        UniswapTwapPriceOracle_SushiSwap: string;
        UniswapV3TwapPriceOracle_Uniswap_3000: string;
        UniswapV3TwapPriceOracleV2_Uniswap_10000_USDC: string;
        UniswapV3TwapPriceOracleV2: string;
        YVaultV1PriceOracle: string;
        YVaultV2PriceOracle: string;
        MasterPriceOracleV1: string;
        MasterPriceOracleV2: string;
        MasterPriceOracleV3: string;
        CurveLpTokenPriceOracle: string;
        CurveLiquidityGaugeV2PriceOracle: string;
        FixedEthPriceOracle: string;
        FixedEurPriceOracle: string;
        WSTEthPriceOracle: string;
        FixedTokenPriceOracle_OHM: string;
        UniswapTwapPriceOracleV2_SushiSwap_DAI: string;
        SushiBarPriceOracle: string;
    };
    static ORACLES: string[];
    static PUBLIC_INTEREST_RATE_MODEL_CONTRACT_ADDRESSES: {
        JumpRateModel_Compound_Stables: string;
        JumpRateModel_Compound_UNI: string;
        JumpRateModel_Cream_Stables_Majors: string;
        JumpRateModel_Cream_Gov_Seeds: string;
        WhitePaperInterestRateModel_Compound_ETH: string;
        WhitePaperInterestRateModel_Compound_WBTC: string;
        JumpRateModel_Fei_FEI: string;
        JumpRateModel_Fei_TRIBE: string;
        JumpRateModel_Fei_ETH: string;
        JumpRateModel_Fei_DAI: string;
        JumpRateModel_Olympus_Majors: string;
        Custom_JumpRateModel: string;
        Custom_JumpRateModel1: string;
    };
    static COMPTROLLER_ERROR_CODES: string[];
    static CTOKEN_ERROR_CODES: string[];
    constructor(web3Provider: JsonRpcProvider | Web3Provider);
}
export {};
